baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[params]
#Google Maps API Key
googleMapsApiKey = "AIzaSyDgQ16eLKZWmPyXDImShJE3yB4wlJRntaI"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "posts"
    url  = "/posts/"
    weight = 2